### ISSUE TITLE
win10下用qt creator编译，报错，用的是mingw32-make。

### ISSUE THREAD

**Issue by Any012** [Embdefire/ebf_linux_qt_demo#1]
:-1: error: No rule to make target '../../ebf_linux_qt_demo/Skin/images/weather/background/???.png', needed by 'debug/qrc_images.o'.  Stop.
:-1: error: cannot find -lSkin
collect2.exe:-1: error: error: ld returned 1 exit status

**Comment by nigoole** [comment]
重新执行再Skin右键执行qmake，再重新构建即可！

**Comment by jiejieTop** [comment]
@Any012 这是乱码问题，好像无解，用其他qt creator版本试试？5.11？
