### ISSUE TITLE
无法定位程序输入点_ZN9QDateTimerC1EOS_

### ISSUE THREAD

**Issue by xiedonghuilove** [Embdefire/ebf_linux_qt_demo#3]
操作系统：Win7
环境：QtCreator-Qt5.7.0 MingW-32bit
火哥，能编译成功，但是不能运行 ，提示“无法定位程序输入点_ZN9QDateTimerC1EOS_”，感觉相似缺少一个库啊。但是查看了源码，有没有看到哪里使用了这个库。
![image](https://user-images.githubusercontent.com/21071102/68738708-fa39c980-0621-11ea-916e-8eaa7fa0b581.png)

**Comment by xiedonghuilove** [comment]
找到问题了，把系统设置的模块关闭就好了，因为，在这里面调用了linux的东西，win7上面没有，
![image](https://user-images.githubusercontent.com/21071102/68759781-5533e680-064b-11ea-8fc9-438326f66502.png)

**Comment by nigoole** [comment]
该Demo做了windows系统兼容编译的，有用到linux相关的东西都是添加了宏定义进行区分的！问题不在这。
