### ISSUE TITLE
按照redeme的步骤编译报错

### ISSUE THREAD

**Issue by hanshuaipeng** [Embdefire/ebf_linux_qt_demo#4]
/opt/fsl-imx-x11/4.1.15-2.1.0/sysroots/x86_64-pokysdk-linux/usr/libexec/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/5.3.0/real-ld:/home/han/linux/imx6ull/ebf_linux_qt_demo/ffmpeg/linuxlib//libavfilter.so:1: syntax error
collect2: error: ld returned 1 exit status
Makefile:685: recipe for target '../app_bin/App' failed
make[1]: *** [../app_bin/App] Error 1
make[1]: Leaving directory '/home/han/linux/imx6ull/ebf_linux_qt_demo/App'
Makefile:94: recipe for target 'sub-App-make_first' failed
make: *** [sub-App-make_first] Error 2
cp: 无法获取'../app_bin/App' 的文件状态(stat): 没有那个文件或目录

编译保存内容如上，按照readme的说的编译的，最后报错

**Comment by jiejieTop** [comment]
先安装 `fsl-imx-x11-glibc-x86_64-meta-toolchain-qt5-cortexa7hf-neon-toolchain-4.1.15-2.1.0.sh`工具链，确保已经存在这个编译工具，然后直接运行编译脚本 `./build.sh` ，应该没什么问题的~

**Comment by hanshuaipeng** [comment]
安装了的，跟步骤操作都一样，结果也一样，只是编译不通过

**Comment by hanshuaipeng** [comment]
> 先安装 `fsl-imx-x11-glibc-x86_64-meta-toolchain-qt5-cortexa7hf-neon-toolchain-4.1.15-2.1.0.sh`工具链，确保已经存在这个编译工具，然后直接运行编译脚本 `./build.sh` ，应该没什么问题的~

安装了的，跟步骤操作都一样，结果也一样，只是编译不通过

**Comment by jiejieTop** [comment]
> > 先安装 `fsl-imx-x11-glibc-x86_64-meta-toolchain-qt5-cortexa7hf-neon-toolchain-4.1.15-2.1.0.sh`工具链，确保已经存在这个编译工具，然后直接运行编译脚本 `./build.sh` ，应该没什么问题的~
> 
> 安装了的，跟步骤操作都一样，结果也一样，只是编译不通过

目前没遇到你这个问题~比较尴尬

**Comment by hanshuaipeng** [comment]
> 目前没遇到你这个问题~比较尴尬

有空可否远程看一下啊

**Comment by jiejieTop** [comment]
> > 目前没遇到你这个问题~比较尴尬
> 
> 有空可否远程看一下啊

我应该知道是怎么回事了，你可能是拉取到Windows然后再拷贝到linux上编译，然后才会出错的，你要直接从GitHub拉取到linux上再编译，不要经过Windows，如果觉得GitHub太慢，gitee也有仓库：[https://gitee.com/wildfireteam/ebf_linux_qt_demo.git](https://gitee.com/wildfireteam/ebf_linux_qt_demo.git)
